default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 10000
  port: 5432

development:
  <<: *default
  host: localhost
  database: playfootball_dev

test:
  <<: *default
  database: playfootball_test

production:
  <<: *default
  host     : app-766efa18-60be-43a1-9294-61d04776b54f-do-user-12551161-0.b.db.ondigitalocean.com
  port     : 25060
  username : db-playfootball-prod
  password : AVNS_uFhtBoBablqWRSP4SgW
  database : db-playfootball-prod